title: Cybersecurity portfolio - adi7312


description:
  <script src="https://tryhackme.com/badge/1373347"></script>


markdown: kramdown
theme: minima

minima:
  - { platform: github, user_url: "https://github.com/adi7312" }


header_pages:
   - CTF.md   
   - NetSec.md
