title: Cybersecurity portfolio - adi7312


description:
  Some cyber stuff.


markdown: kramdown
theme: minima

minima:
  - { platform: github, user_url: "https://github.com/adi7312" }


header_pages:
   - CTF.md   
   - NetSec.md
