title: Cybersecurity portfolio - adi7312


description: >
  Repository contains solutions to CTF tasks, cybersecurity projects and much more cyber staff!


markdown: kramdown
theme: minima

minima:
  skin: dark
  - { platform: github, user_url: "https://github.com/adi7312" }


header_pages:
   - CTF.md   
   - NetSec.md
